title: Nishan Rayamajhee
email: nishan@rayamajhee.com
description: >
    Everyone needs a dot com; this is mine—for now (hopefully not for ever).
url: "https://nishan.rayamajhee.com"
username: nrayamajhee
google_analytics: UA-122012177-1

# Build settings
markdown: kramdown
