title: Nishan Rayamajhee
email: nishan@rayamajhee.com
description: >
    Everyone needs a dot com; this is mine—for now (hopefully not for ever).
url: "http://nishan.rayamajhee.com"
username: nrayamajhee

# Build settings
markdown: kramdown
